### ISSUE TITLE
SurveyGizmo  Grid question types

### ISSUE THREAD

**Issue by vincent1892** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#15]
Hi, 

I've been trying to figure out how to use this Library to create Table-radio, Table-checkbox etc. I can add the options (Columns) but cannot seem to add the Rows (sub_questions), please help?

Best,
Vincent

**Comment by SurveyGizmoOfficial** [comment]
Hi Vincent,
You'll need to do a put on the overall table question in order to create row subquestions like so:

https://restapi.surveygizmo.com/v4/survey/123456/surveypage/1/surveyquestion/2?_method=PUT&type=radio&title=Twitter

Here's a help article with more info:
[https://apihelp.surveygizmo.com/help/create-table-question](https://apihelp.surveygizmo.com/help/create-table-question)

Cheers!

The SurveyGizmo Team
